language: python

virtualenv:
  system_site_packages: true

python:
  - 2.6
  - 2.7

before_install:
 - sudo apt-get install -qq python-numpy python-scipy

install:
  - pip install -r requirements.txt
  - python setup.py install

script: pyssim test-images/test1-1.png test-images/test1-2.png
