language: python

python:
  - 2.7
  - 3.3
  - 3.4

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes -q -n pyenv python=$TRAVIS_PYTHON_VERSION pillow numpy scipy nose pylint pip
  - source activate pyenv
  - pip install -e .

script:
 - pyssim test-images/test1-1.png test-images/test1-1.png | grep 1
 - pyssim test-images/test1-1.png test-images/test1-2.png | grep 0.998
 - pyssim test-images/test1-1.png "test-images/*" | grep -E " 1| 0.998| 0.673| 0.648" | wc -l | grep 4
 - pyssim --cw --width 128 --height 128 test-images/test1-1.png test-images/test1-1.png | grep 1
 - pyssim --cw --width 128 --height 128 test-images/test3-orig.jpg test-images/test3-rot.jpg | grep 0.938
 - pylint --rcfile=.pylintrc setup.py
 - pylint --rcfile=.pylintrc ssim
